# For Atom Feed
domain: cleancocoa.com
author: Christian Tietze

# Site settings
title: Clean Cocoa
email: hi@christiantietze.de
description: >
  Find out how to craft maintainable iOS and macOS applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cleancocoa.com" # the base hostname & protocol for your site
twitter_username: ctietze
github_username:  cleancocoa

# Build settings
markdown: kramdown
exclude: ['Rakefile', 'Gemfile.lock', 'Gemfile']
lang: en
timezone: Germany/Berlin

# Posts
permalink: /posts/:year/:month/:title/

collections:
  wiki:
    output: true
    permalink: /wiki/:title/

defaults: 
  - scope:
      path: ""
      type: posts
    values: 
      layout: post
      author: ct
  - scope:
      path: ""
      type: wiki
    values: 
      layout: wiki
  - scope: # default
      path: ""
    values:
      layout: default
